INSERT INTO Products (quantity, Name, Image, Price, Description, Category) VALUES
(10,'Greek salad', 'food_1.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Salad'),
(10,'Veg salad', 'food_2.png', 18, 'Food provides essential nutrients for overall health and well-being', 'Salad'),
(10,'Clover Salad', 'food_3.png', 16, 'Food provides essential nutrients for overall health and well-being', 'Salad'),
(10,'Chicken Salad', 'food_4.png', 24, 'Food provides essential nutrients for overall health and well-being', 'Salad'),
(10,'Lasagna Rolls', 'food_5.png', 14, 'Food provides essential nutrients for overall health and well-being', 'Rolls'),
(10,'Peri Peri Rolls', 'food_6.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Rolls'),
(10,'Chicken Rolls', 'food_7.png', 20, 'Food provides essential nutrients for overall health and well-being', 'Rolls'),
(10,'Veg Rolls', 'food_8.png', 15, 'Food provides essential nutrients for overall health and well-being', 'Rolls'),
(10,'Ripple Ice Cream', 'food_9.png', 14, 'Food provides essential nutrients for overall health and well-being', 'Deserts'),
(10,'Fruit Ice Cream', 'food_10.png', 22, 'Food provides essential nutrients for overall health and well-being', 'Deserts'),
(10,'Jar Ice Cream', 'food_11.png', 10, 'Food provides essential nutrients for overall health and well-being', 'Deserts'),
(10,'Vanilla Ice Cream', 'food_12.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Deserts'),
(10,'Chicken Sandwich', 'food_13.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Sandwich'),
(10,'Vegan Sandwich', 'food_14.png', 18, 'Food provides essential nutrients for overall health and well-being', 'Sandwich'),
(10,'Grilled Sandwich', 'food_15.png', 16, 'Food provides essential nutrients for overall health and well-being', 'Sandwich'),
(10,'Bread Sandwich', 'food_16.png', 24, 'Food provides essential nutrients for overall health and well-being', 'Sandwich'),
(10,'Cup Cake', 'food_17.png', 14, 'Food provides essential nutrients for overall health and well-being', 'Cake'),
(10,'Vegan Cake', 'food_18.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Cake'),
(10,'Butterscotch Cake', 'food_19.png', 20, 'Food provides essential nutrients for overall health and well-being', 'Cake'),
(10,'Sliced Cake', 'food_20.png', 15, 'Food provides essential nutrients for overall health and well-being', 'Cake'),
(10,'Garlic Mushroom', 'food_21.png', 14, 'Food provides essential nutrients for overall health and well-being', 'Pure Veg'),
(10,'Fried Cauliflower', 'food_22.png', 22, 'Food provides essential nutrients for overall health and well-being', 'Pure Veg'),
(10,'Mix Veg Pulao', 'food_23.png', 10, 'Food provides essential nutrients for overall health and well-being', 'Pure Veg'),
(10,'Rice Zucchini', 'food_24.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Pure Veg'),
(10,'Cheese Pasta', 'food_25.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Pasta'),
(10,'Tomato Pasta', 'food_26.png', 18, 'Food provides essential nutrients for overall health and well-being', 'Pasta'),
(10,'Creamy Pasta', 'food_27.png', 16, 'Food provides essential nutrients for overall health and well-being', 'Pasta'),
(10,'Chicken Pasta', 'food_28.png', 24, 'Food provides essential nutrients for overall health and well-being', 'Pasta'),
(10,'Buttter Noodles', 'food_29.png', 14, 'Food provides essential nutrients for overall health and well-being', 'Noodles'),
(10,'Veg Noodles', 'food_30.png', 12, 'Food provides essential nutrients for overall health and well-being', 'Noodles'),
(10,'Somen Noodles', 'food_31.png', 20, 'Food provides essential nutrients for overall health and well-being', 'Noodles'),
(10,'Cooked Noodles', 'food_32.png', 15, 'Food provides essential nutrients for overall health and well-being', 'Noodles');
